// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
WHERE villa_slug = $1
`

func (q *Queries) CountAuditEvents(ctx context.Context, villaSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents, villaSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (id, villa_slug, type, message, actor_email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, villa_slug, type, message, actor_email, created_at
`

type InsertAuditEventParams struct {
	ID         pgtype.UUID
	VillaSlug  string
	Type       AuditEventType
	Message    string
	ActorEmail string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.VillaSlug,
		arg.Type,
		arg.Message,
		arg.ActorEmail,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.Type,
		&i.Message,
		&i.ActorEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, villa_slug, type, message, actor_email, created_at FROM audit_events
WHERE villa_slug = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditEventsParams struct {
	VillaSlug string
	Off       int32
	Lim       int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.VillaSlug, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.Type,
			&i.Message,
			&i.ActorEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
