// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBookings = `-- name: CountBookings :one
SELECT COUNT(*) FROM bookings
`

func (q *Queries) CountBookings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBookings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByStatus = `-- name: CountBookingsByStatus :one
SELECT COUNT(*) FROM bookings WHERE status = $1
`

func (q *Queries) CountBookingsByStatus(ctx context.Context, status BookingStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByVilla = `-- name: CountBookingsByVilla :one
SELECT COUNT(*) FROM bookings WHERE villa_slug = $1
`

func (q *Queries) CountBookingsByVilla(ctx context.Context, villaSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByVilla, villaSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByVillaAndStatus = `-- name: CountBookingsByVillaAndStatus :one
SELECT COUNT(*) FROM bookings WHERE villa_slug = $1 AND status = $2
`

type CountBookingsByVillaAndStatusParams struct {
	VillaSlug string
	Status    BookingStatus
}

func (q *Queries) CountBookingsByVillaAndStatus(ctx context.Context, arg CountBookingsByVillaAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByVillaAndStatus, arg.VillaSlug, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBooking = `-- name: DeleteBooking :execrows
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBooking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOverlappingBookings = `-- name: FindOverlappingBookings :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
WHERE villa_slug = $1
  AND status IN ('pending', 'approved', 'paid')
  AND check_in  < $3
  AND check_out > $2
`

type FindOverlappingBookingsParams struct {
	VillaSlug string
	CheckOut  pgtype.Date
	CheckIn   pgtype.Date
}

func (q *Queries) FindOverlappingBookings(ctx context.Context, arg FindOverlappingBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, findOverlappingBookings, arg.VillaSlug, arg.CheckOut, arg.CheckIn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (
    id, villa_slug, guest_name, guest_email, guest_phone,
    check_in, check_out, adults, children, message, status, source
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source
`

type InsertBookingParams struct {
	ID         pgtype.UUID
	VillaSlug  string
	GuestName  string
	GuestEmail string
	GuestPhone string
	CheckIn    pgtype.Date
	CheckOut   pgtype.Date
	Adults     int16
	Children   int16
	Message    string
	Status     BookingStatus
	Source     string
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.ID,
		arg.VillaSlug,
		arg.GuestName,
		arg.GuestEmail,
		arg.GuestPhone,
		arg.CheckIn,
		arg.CheckOut,
		arg.Adults,
		arg.Children,
		arg.Message,
		arg.Status,
		arg.Source,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const listBookedRanges = `-- name: ListBookedRanges :many
SELECT check_in, check_out FROM bookings
WHERE villa_slug = $1
  AND status IN ('approved', 'paid')
  AND check_in  < $3
  AND check_out > $2
ORDER BY check_in
`

type ListBookedRangesParams struct {
	VillaSlug string
	CheckOut  pgtype.Date
	CheckIn   pgtype.Date
}

type ListBookedRangesRow struct {
	CheckIn  pgtype.Date
	CheckOut pgtype.Date
}

func (q *Queries) ListBookedRanges(ctx context.Context, arg ListBookedRangesParams) ([]ListBookedRangesRow, error) {
	rows, err := q.db.Query(ctx, listBookedRanges, arg.VillaSlug, arg.CheckOut, arg.CheckIn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookedRangesRow
	for rows.Next() {
		var i ListBookedRangesRow
		if err := rows.Scan(&i.CheckIn, &i.CheckOut); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByStatus(ctx context.Context, status BookingStatus) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsPaged = `-- name: ListBookingsPaged :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBookingsPagedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBookingsPaged(ctx context.Context, arg ListBookingsPagedParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsPagedByStatus = `-- name: ListBookingsPagedByStatus :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsPagedByStatusParams struct {
	Status BookingStatus
	Limit  int32
	Offset int32
}

func (q *Queries) ListBookingsPagedByStatus(ctx context.Context, arg ListBookingsPagedByStatusParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsPagedByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsPagedByVilla = `-- name: ListBookingsPagedByVilla :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
WHERE villa_slug = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsPagedByVillaParams struct {
	VillaSlug string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListBookingsPagedByVilla(ctx context.Context, arg ListBookingsPagedByVillaParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsPagedByVilla, arg.VillaSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsPagedByVillaAndStatus = `-- name: ListBookingsPagedByVillaAndStatus :many
SELECT id, villa_slug, guest_name, guest_email, guest_phone, check_in, check_out, adults, children, message, status, created_at, updated_at, source FROM bookings
WHERE villa_slug = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListBookingsPagedByVillaAndStatusParams struct {
	VillaSlug string
	Status    BookingStatus
	Limit     int32
	Offset    int32
}

func (q *Queries) ListBookingsPagedByVillaAndStatus(ctx context.Context, arg ListBookingsPagedByVillaAndStatusParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsPagedByVillaAndStatus,
		arg.VillaSlug,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRanges = `-- name: ListPendingRanges :many
SELECT check_in, check_out FROM bookings
WHERE villa_slug = $1
  AND status = 'pending'
  AND check_in  < $3
  AND check_out > $2
ORDER BY check_in
`

type ListPendingRangesParams struct {
	VillaSlug string
	CheckOut  pgtype.Date
	CheckIn   pgtype.Date
}

type ListPendingRangesRow struct {
	CheckIn  pgtype.Date
	CheckOut pgtype.Date
}

func (q *Queries) ListPendingRanges(ctx context.Context, arg ListPendingRangesParams) ([]ListPendingRangesRow, error) {
	rows, err := q.db.Query(ctx, listPendingRanges, arg.VillaSlug, arg.CheckOut, arg.CheckIn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRangesRow
	for rows.Next() {
		var i ListPendingRangesRow
		if err := rows.Scan(&i.CheckIn, &i.CheckOut); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings
SET status = $2, updated_at = $3
WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID        pgtype.UUID
	Status    BookingStatus
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
