// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSeasonRule = `-- name: DeleteSeasonRule :execrows
DELETE FROM season_rules WHERE id = $1
`

func (q *Queries) DeleteSeasonRule(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeasonRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPricingSettings = `-- name: GetPricingSettings :one
SELECT villa_slug, base_price_cents, min_nights, cleaning_fee_cents, concierge_fee_cents, created_at, updated_at FROM villa_pricing_settings
WHERE villa_slug = $1
`

func (q *Queries) GetPricingSettings(ctx context.Context, villaSlug string) (VillaPricingSetting, error) {
	row := q.db.QueryRow(ctx, getPricingSettings, villaSlug)
	var i VillaPricingSetting
	err := row.Scan(
		&i.VillaSlug,
		&i.BasePriceCents,
		&i.MinNights,
		&i.CleaningFeeCents,
		&i.ConciergeFeeCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeasonRule = `-- name: GetSeasonRule :one
SELECT id, villa_slug, label, start_date, end_date, price_cents, created_at, updated_at FROM season_rules
WHERE id = $1
`

func (q *Queries) GetSeasonRule(ctx context.Context, id pgtype.UUID) (SeasonRule, error) {
	row := q.db.QueryRow(ctx, getSeasonRule, id)
	var i SeasonRule
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.Label,
		&i.StartDate,
		&i.EndDate,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSeasonRule = `-- name: InsertSeasonRule :one
INSERT INTO season_rules (id, villa_slug, label, start_date, end_date, price_cents)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, villa_slug, label, start_date, end_date, price_cents, created_at, updated_at
`

type InsertSeasonRuleParams struct {
	ID         pgtype.UUID
	VillaSlug  string
	Label      string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	PriceCents int32
}

func (q *Queries) InsertSeasonRule(ctx context.Context, arg InsertSeasonRuleParams) (SeasonRule, error) {
	row := q.db.QueryRow(ctx, insertSeasonRule,
		arg.ID,
		arg.VillaSlug,
		arg.Label,
		arg.StartDate,
		arg.EndDate,
		arg.PriceCents,
	)
	var i SeasonRule
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.Label,
		&i.StartDate,
		&i.EndDate,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSeasonRules = `-- name: ListSeasonRules :many
SELECT id, villa_slug, label, start_date, end_date, price_cents, created_at, updated_at FROM season_rules
WHERE villa_slug = $1
ORDER BY start_date
`

func (q *Queries) ListSeasonRules(ctx context.Context, villaSlug string) ([]SeasonRule, error) {
	rows, err := q.db.Query(ctx, listSeasonRules, villaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonRule
	for rows.Next() {
		var i SeasonRule
		if err := rows.Scan(
			&i.ID,
			&i.VillaSlug,
			&i.Label,
			&i.StartDate,
			&i.EndDate,
			&i.PriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonRule = `-- name: UpdateSeasonRule :one
UPDATE season_rules
SET label       = COALESCE($1, label),
    start_date  = COALESCE($2, start_date),
    end_date    = COALESCE($3, end_date),
    price_cents = COALESCE($4, price_cents),
    updated_at  = NOW()
WHERE id = $5
RETURNING id, villa_slug, label, start_date, end_date, price_cents, created_at, updated_at
`

type UpdateSeasonRuleParams struct {
	Label      *string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	PriceCents *int32
	ID         pgtype.UUID
}

func (q *Queries) UpdateSeasonRule(ctx context.Context, arg UpdateSeasonRuleParams) (SeasonRule, error) {
	row := q.db.QueryRow(ctx, updateSeasonRule,
		arg.Label,
		arg.StartDate,
		arg.EndDate,
		arg.PriceCents,
		arg.ID,
	)
	var i SeasonRule
	err := row.Scan(
		&i.ID,
		&i.VillaSlug,
		&i.Label,
		&i.StartDate,
		&i.EndDate,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPricingSettings = `-- name: UpsertPricingSettings :one
INSERT INTO villa_pricing_settings (
    villa_slug, base_price_cents, min_nights, cleaning_fee_cents, concierge_fee_cents
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (villa_slug) DO UPDATE
SET base_price_cents    = EXCLUDED.base_price_cents,
    min_nights          = EXCLUDED.min_nights,
    cleaning_fee_cents  = EXCLUDED.cleaning_fee_cents,
    concierge_fee_cents = EXCLUDED.concierge_fee_cents,
    updated_at          = NOW()
RETURNING villa_slug, base_price_cents, min_nights, cleaning_fee_cents, concierge_fee_cents, created_at, updated_at
`

type UpsertPricingSettingsParams struct {
	VillaSlug         string
	BasePriceCents    int32
	MinNights         int16
	CleaningFeeCents  int32
	ConciergeFeeCents int32
}

func (q *Queries) UpsertPricingSettings(ctx context.Context, arg UpsertPricingSettingsParams) (VillaPricingSetting, error) {
	row := q.db.QueryRow(ctx, upsertPricingSettings,
		arg.VillaSlug,
		arg.BasePriceCents,
		arg.MinNights,
		arg.CleaningFeeCents,
		arg.ConciergeFeeCents,
	)
	var i VillaPricingSetting
	err := row.Scan(
		&i.VillaSlug,
		&i.BasePriceCents,
		&i.MinNights,
		&i.CleaningFeeCents,
		&i.ConciergeFeeCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
