// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPriceOverrides = `-- name: ListPriceOverrides :many
SELECT villa_slug, date, price_cents
FROM price_overrides
WHERE villa_slug = $1
  AND date >= $2
  AND date < $3
ORDER BY date
`

type ListPriceOverridesParams struct {
	VillaSlug string
	From      pgtype.Date
	To        pgtype.Date
}

type ListPriceOverridesRow struct {
	VillaSlug  string
	Date       pgtype.Date
	PriceCents int32
}

func (q *Queries) ListPriceOverrides(ctx context.Context, arg ListPriceOverridesParams) ([]ListPriceOverridesRow, error) {
	rows, err := q.db.Query(ctx, listPriceOverrides, arg.VillaSlug, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceOverridesRow
	for rows.Next() {
		var i ListPriceOverridesRow
		if err := rows.Scan(&i.VillaSlug, &i.Date, &i.PriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPriceOverride = `-- name: UpsertPriceOverride :exec
INSERT INTO price_overrides (villa_slug, date, price_cents)
VALUES ($1, $2, $3)
ON CONFLICT (villa_slug, date) DO UPDATE
SET price_cents = EXCLUDED.price_cents,
    updated_at = NOW()
`

type UpsertPriceOverrideParams struct {
	VillaSlug  string
	Date       pgtype.Date
	PriceCents int32
}

func (q *Queries) UpsertPriceOverride(ctx context.Context, arg UpsertPriceOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertPriceOverride, arg.VillaSlug, arg.Date, arg.PriceCents)
	return err
}
