// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountBookings(ctx context.Context) (int64, error)
	CountBookingsByStatus(ctx context.Context, status BookingStatus) (int64, error)
	CountBookingsByVilla(ctx context.Context, villaSlug string) (int64, error)
	CountBookingsByVillaAndStatus(ctx context.Context, arg CountBookingsByVillaAndStatusParams) (int64, error)
	DeleteAdminUser(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteBooking(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteReview(ctx context.Context, id pgtype.UUID) (int64, error)
	FindOverlappingBookings(ctx context.Context, arg FindOverlappingBookingsParams) ([]Booking, error)
	FindOverlappingConfirmedBookings(ctx context.Context, arg FindOverlappingConfirmedBookingsParams) ([]Booking, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminUserByID(ctx context.Context, id pgtype.UUID) (AdminUser, error)
	GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error)
	InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (AdminUser, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error)
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListBookedRanges(ctx context.Context, arg ListBookedRangesParams) ([]ListBookedRangesRow, error)
	ListBookingsByStatus(ctx context.Context, status BookingStatus) ([]Booking, error)
	ListBookingsPaged(ctx context.Context, arg ListBookingsPagedParams) ([]Booking, error)
	ListBookingsPagedByStatus(ctx context.Context, arg ListBookingsPagedByStatusParams) ([]Booking, error)
	ListBookingsPagedByVilla(ctx context.Context, arg ListBookingsPagedByVillaParams) ([]Booking, error)
	ListBookingsPagedByVillaAndStatus(ctx context.Context, arg ListBookingsPagedByVillaAndStatusParams) ([]Booking, error)
	ListPendingRanges(ctx context.Context, arg ListPendingRangesParams) ([]ListPendingRangesRow, error)
	ListPriceOverrides(ctx context.Context, arg ListPriceOverridesParams) ([]ListPriceOverridesRow, error)
	ListReviewsByVilla(ctx context.Context, villaSlug string) ([]Review, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpsertPriceOverride(ctx context.Context, arg UpsertPriceOverrideParams) error
}

var _ Querier = (*Queries)(nil)
