// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAuditEvents(ctx context.Context, villaSlug string) (int64, error)
	CountBookings(ctx context.Context) (int64, error)
	CountBookingsByStatus(ctx context.Context, status BookingStatus) (int64, error)
	CountBookingsByVilla(ctx context.Context, villaSlug string) (int64, error)
	CountBookingsByVillaAndStatus(ctx context.Context, arg CountBookingsByVillaAndStatusParams) (int64, error)
	DeleteAdminUser(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteBooking(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteReview(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteSeasonRule(ctx context.Context, id pgtype.UUID) (int64, error)
	FindOverlappingBookings(ctx context.Context, arg FindOverlappingBookingsParams) ([]Booking, error)
	FindOverlappingConfirmedBookings(ctx context.Context, arg FindOverlappingConfirmedBookingsParams) ([]Booking, error)
	GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	GetAdminUserByID(ctx context.Context, id pgtype.UUID) (AdminUser, error)
	GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error)
	GetPricingSettings(ctx context.Context, villaSlug string) (VillaPricingSetting, error)
	GetReview(ctx context.Context, id pgtype.UUID) (Review, error)
	GetSeasonRule(ctx context.Context, id pgtype.UUID) (SeasonRule, error)
	// The villa's published rating, computed from its approved reviews only: a
	// review that is pending or hidden contributes nothing, and approving one folds
	// it straight in. The per-category AVGs skip NULLs, so each category is averaged
	// over the reviews that actually scored it and reads back NULL when none did.
	GetVillaReviewAggregate(ctx context.Context, villaSlug string) (GetVillaReviewAggregateRow, error)
	InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (AdminUser, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error)
	InsertSeasonRule(ctx context.Context, arg InsertSeasonRuleParams) (SeasonRule, error)
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListBookedRanges(ctx context.Context, arg ListBookedRangesParams) ([]ListBookedRangesRow, error)
	ListBookingsByStatus(ctx context.Context, status BookingStatus) ([]Booking, error)
	ListBookingsPaged(ctx context.Context, arg ListBookingsPagedParams) ([]Booking, error)
	ListBookingsPagedByStatus(ctx context.Context, arg ListBookingsPagedByStatusParams) ([]Booking, error)
	ListBookingsPagedByVilla(ctx context.Context, arg ListBookingsPagedByVillaParams) ([]Booking, error)
	ListBookingsPagedByVillaAndStatus(ctx context.Context, arg ListBookingsPagedByVillaAndStatusParams) ([]Booking, error)
	ListPendingRanges(ctx context.Context, arg ListPendingRangesParams) ([]ListPendingRangesRow, error)
	ListPriceOverrides(ctx context.Context, arg ListPriceOverridesParams) ([]ListPriceOverridesRow, error)
	ListReviewsByVilla(ctx context.Context, villaSlug string) ([]Review, error)
	ListReviewsByVillaAndStatus(ctx context.Context, arg ListReviewsByVillaAndStatusParams) ([]Review, error)
	ListSeasonRules(ctx context.Context, villaSlug string) ([]SeasonRule, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateSeasonRule(ctx context.Context, arg UpdateSeasonRuleParams) (SeasonRule, error)
	UpsertPriceOverride(ctx context.Context, arg UpsertPriceOverrideParams) error
	UpsertPricingSettings(ctx context.Context, arg UpsertPricingSettingsParams) (VillaPricingSetting, error)
}

var _ Querier = (*Queries)(nil)
