// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (id, booking_id, villa_slug, author_name, rating, body, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at
`

type InsertReviewParams struct {
	ID         pgtype.UUID
	BookingID  pgtype.UUID
	VillaSlug  string
	AuthorName string
	Rating     int16
	Body       string
	Status     ReviewStatus
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ID,
		arg.BookingID,
		arg.VillaSlug,
		arg.AuthorName,
		arg.Rating,
		arg.Body,
		arg.Status,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.VillaSlug,
		&i.AuthorName,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByVilla = `-- name: ListReviewsByVilla :many
SELECT id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at FROM reviews
WHERE villa_slug = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByVilla(ctx context.Context, villaSlug string) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByVilla, villaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.VillaSlug,
			&i.AuthorName,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
