// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReview = `-- name: GetReview :one
SELECT id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at, featured, meta, source, rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.VillaSlug,
		&i.AuthorName,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Featured,
		&i.Meta,
		&i.Source,
		&i.RatingCleanliness,
		&i.RatingComfort,
		&i.RatingLocation,
		&i.RatingHost,
		&i.RatingValue,
	)
	return i, err
}

const getVillaReviewAggregate = `-- name: GetVillaReviewAggregate :one
SELECT
    COUNT(*)                          AS review_count,
    AVG(rating)::numeric              AS avg_rating,
    AVG(rating_cleanliness)::numeric  AS avg_cleanliness,
    AVG(rating_comfort)::numeric      AS avg_comfort,
    AVG(rating_location)::numeric     AS avg_location,
    AVG(rating_host)::numeric         AS avg_host,
    AVG(rating_value)::numeric        AS avg_value
FROM reviews
WHERE villa_slug = $1 AND status = 'approved'
`

type GetVillaReviewAggregateRow struct {
	ReviewCount    int64
	AvgRating      pgtype.Numeric
	AvgCleanliness pgtype.Numeric
	AvgComfort     pgtype.Numeric
	AvgLocation    pgtype.Numeric
	AvgHost        pgtype.Numeric
	AvgValue       pgtype.Numeric
}

// The villa's published rating, computed from its approved reviews only: a
// review that is pending or hidden contributes nothing, and approving one folds
// it straight in. The per-category AVGs skip NULLs, so each category is averaged
// over the reviews that actually scored it and reads back NULL when none did.
func (q *Queries) GetVillaReviewAggregate(ctx context.Context, villaSlug string) (GetVillaReviewAggregateRow, error) {
	row := q.db.QueryRow(ctx, getVillaReviewAggregate, villaSlug)
	var i GetVillaReviewAggregateRow
	err := row.Scan(
		&i.ReviewCount,
		&i.AvgRating,
		&i.AvgCleanliness,
		&i.AvgComfort,
		&i.AvgLocation,
		&i.AvgHost,
		&i.AvgValue,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (
    id, booking_id, villa_slug, author_name, rating, body, status, meta, source, featured,
    rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at, featured, meta, source, rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value
`

type InsertReviewParams struct {
	ID                pgtype.UUID
	BookingID         pgtype.UUID
	VillaSlug         string
	AuthorName        string
	Rating            int16
	Body              string
	Status            ReviewStatus
	Meta              string
	Source            string
	Featured          bool
	RatingCleanliness pgtype.Numeric
	RatingComfort     pgtype.Numeric
	RatingLocation    pgtype.Numeric
	RatingHost        pgtype.Numeric
	RatingValue       pgtype.Numeric
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.ID,
		arg.BookingID,
		arg.VillaSlug,
		arg.AuthorName,
		arg.Rating,
		arg.Body,
		arg.Status,
		arg.Meta,
		arg.Source,
		arg.Featured,
		arg.RatingCleanliness,
		arg.RatingComfort,
		arg.RatingLocation,
		arg.RatingHost,
		arg.RatingValue,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.VillaSlug,
		&i.AuthorName,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Featured,
		&i.Meta,
		&i.Source,
		&i.RatingCleanliness,
		&i.RatingComfort,
		&i.RatingLocation,
		&i.RatingHost,
		&i.RatingValue,
	)
	return i, err
}

const listReviewsByVilla = `-- name: ListReviewsByVilla :many
SELECT id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at, featured, meta, source, rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value FROM reviews
WHERE villa_slug = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByVilla(ctx context.Context, villaSlug string) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByVilla, villaSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.VillaSlug,
			&i.AuthorName,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Featured,
			&i.Meta,
			&i.Source,
			&i.RatingCleanliness,
			&i.RatingComfort,
			&i.RatingLocation,
			&i.RatingHost,
			&i.RatingValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByVillaAndStatus = `-- name: ListReviewsByVillaAndStatus :many
SELECT id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at, featured, meta, source, rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value FROM reviews
WHERE villa_slug = $1
  AND ($2::review_status IS NULL OR status = $2::review_status)
ORDER BY featured DESC, created_at DESC
`

type ListReviewsByVillaAndStatusParams struct {
	VillaSlug string
	Status    *ReviewStatus
}

func (q *Queries) ListReviewsByVillaAndStatus(ctx context.Context, arg ListReviewsByVillaAndStatusParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByVillaAndStatus, arg.VillaSlug, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.VillaSlug,
			&i.AuthorName,
			&i.Rating,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Featured,
			&i.Meta,
			&i.Source,
			&i.RatingCleanliness,
			&i.RatingComfort,
			&i.RatingLocation,
			&i.RatingHost,
			&i.RatingValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET status             = COALESCE($1::review_status, status),
    featured           = COALESCE($2, featured),
    meta               = COALESCE($3, meta),
    source             = COALESCE($4, source),
    body               = COALESCE($5, body),
    rating             = COALESCE($6, rating),
    rating_cleanliness = COALESCE($7, rating_cleanliness),
    rating_comfort     = COALESCE($8, rating_comfort),
    rating_location    = COALESCE($9, rating_location),
    rating_host        = COALESCE($10, rating_host),
    rating_value       = COALESCE($11, rating_value),
    updated_at         = NOW()
WHERE id = $12
RETURNING id, booking_id, villa_slug, author_name, rating, body, status, created_at, updated_at, featured, meta, source, rating_cleanliness, rating_comfort, rating_location, rating_host, rating_value
`

type UpdateReviewParams struct {
	Status            *ReviewStatus
	Featured          *bool
	Meta              *string
	Source            *string
	Body              *string
	Rating            *int16
	RatingCleanliness pgtype.Numeric
	RatingComfort     pgtype.Numeric
	RatingLocation    pgtype.Numeric
	RatingHost        pgtype.Numeric
	RatingValue       pgtype.Numeric
	ID                pgtype.UUID
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Status,
		arg.Featured,
		arg.Meta,
		arg.Source,
		arg.Body,
		arg.Rating,
		arg.RatingCleanliness,
		arg.RatingComfort,
		arg.RatingLocation,
		arg.RatingHost,
		arg.RatingValue,
		arg.ID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.VillaSlug,
		&i.AuthorName,
		&i.Rating,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Featured,
		&i.Meta,
		&i.Source,
		&i.RatingCleanliness,
		&i.RatingComfort,
		&i.RatingLocation,
		&i.RatingHost,
		&i.RatingValue,
	)
	return i, err
}
